settings:
  title: 'Page de status'
  url: 'https://status.raph.fun/*' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Aucun problème'
  notAllmonitorsOperational: 'Problèmes détectés'
  monitorLabelOperational: 'Opérationnel'
  monitorLabelNotOperational: 'Perturbé'
  monitorLabelNoData: 'Pas de données'
  dayInHistogramNoData: 'Pas de données'
  dayInHistogramOperational: 'Tout est OK'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: raphFun # unique identifier
    name: raph.fun
    description: 'La boutique de Raph' # default=empty
    url: 'https://raph.fun/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: AntoTebexIo # unique identifier
    name: anto.tebex.io
    description: 'La boutique d'Anto' # default=empty
    url: 'https://anto.tebex.io/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
